AWSTemplateFormatVersion: '2010-09-09'
Description: Create a MySQL RDS instance with specified configurations

Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: admindb
    Description: Unique identifier for the DB instance
  DBName:
    Type: String
    Default: mysqldb
    Description: Initial name for the database
  DBMasterUsername:
    Type: String
    Default: admin
    Description: Username for the master DB user
  DBMasterPassword:
    Type: String
    Description: Password for the master DB user
    NoEcho: true
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the VPC where RDS instance will be created
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of private subnet IDs for the subnet group

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MySQL RDS instance
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: MySQLRDSSecurityGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for MySQL RDS instance
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: MySQLRDSPrivateSubnetGroup

  DBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DBSecurityGroup
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      EngineVersion: 8.0.35
      DBName: !Ref DBName
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      AllocatedStorage: 20
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: MySQLRDSInstance
